# Keep your existing site metadata...
title: Yifei's Blog
email: zyf0717@gmail.com
description: >-
  Welcome to my blog! Through this platform, I hope to document and share my
  tech journey. To find out more, please click the "About" button at the top
  of this page (or the hamburger button if you are on mobile).
url: https://blog.yifei.sg
baseurl: ""

# IMPORTANT: use remote_theme (not theme:)
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

# Minima v3 skin (dark/light/auto)
minima:
  skin: auto
