title: Yifei's Blog

email: zyf0717@gmail.com

url: https://blog.yifei.sg
baseurl: ""

# Use Minima (v3) via remote_theme
remote_theme: jekyll/minima

# GitHub Pages–allowed plugins only
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Minima v3 skin (dark/light/auto follows system preference)
minima:
  skin: auto
  social_links:
    - title: "Email"
      icon: envelope
      url: "mailto:zyf0717@gmail.com"
